jobs:
	golangci:
	  name: lint
	  runs-on: ubuntu-latest
	  strategy:
		matrix:
		  go-version: ["1.21"]
  
	  steps:
		- uses: actions/setup-go@v3
		  with:
			go-version: ${{ matrix.go-version }}
		- uses: actions/checkout@v3
		- name: golangci-lint
		  uses: golangci/golangci-lint-action@v3
		  with:
			version: v1.54.2
  
	test:
	  name: test
	  runs-on: ubuntu-latest
	  strategy:
		matrix:
		  go-version: ["1.20", "1.21"]
  
	  steps:
		- uses: actions/setup-go@v3
		  with:
			go-version: ${{ matrix.go-version }}
		- uses: actions/checkout@v3
		- name: test
		  run: |
			go test -v -race 
